"""shortfall — a portfolio risk engine, in pure Python with no dependencies."""

from __future__ import annotations

from .covariance import (
    Diagnostics,
    Shrunk,
    average_correlation,
    blend,
    constant_correlation_target,
    correlation,
    diagnose,
    ledoit_wolf,
    portfolio_variance,
    sample_covariance,
)
from .distributions import (
    OutOfDomain,
    normal_cdf,
    normal_pdf,
    normal_ppf,
    student_t_cdf,
    student_t_pdf,
    student_t_ppf,
)
from .historical import (
    Coherence,
    Filtered,
    HistoricalRisk,
    Interval,
    QuantileMethod,
    bootstrap_interval,
    check_subadditivity,
    empirical_quantile,
    ewma_volatility,
    filtered_historical_risk,
    historical_risk,
    sample_expected_shortfall,
)
from .linalg import (
    NotPositiveDefinite,
    NotSquare,
    NotSymmetric,
    cholesky,
    condition_number,
    eigenvalues,
    eigh,
    is_positive_semidefinite,
    nearest_psd,
    quadratic_form,
)
from .parametric import (
    Distribution,
    NotAQuantileFunction,
    Risk,
    cornish_fisher_risk,
    normal_risk,
    parametric_risk,
    portfolio_risk,
    student_t_risk,
)
from .series import (
    ANNUAL,
    DAILY_CALENDAR,
    DAILY_TRADING,
    MONTHLY,
    QUARTERLY,
    WEEKLY,
    Convention,
    Misaligned,
    Panel,
    ReturnSeries,
    TooShort,
)

__version__ = "0.1.0"

__all__ = [
    "ANNUAL",
    "DAILY_CALENDAR",
    "DAILY_TRADING",
    "MONTHLY",
    "QUARTERLY",
    "WEEKLY",
    "Coherence",
    "Convention",
    "Diagnostics",
    "Distribution",
    "Filtered",
    "HistoricalRisk",
    "Interval",
    "Misaligned",
    "NotAQuantileFunction",
    "NotPositiveDefinite",
    "NotSquare",
    "NotSymmetric",
    "OutOfDomain",
    "Panel",
    "QuantileMethod",
    "ReturnSeries",
    "Risk",
    "Shrunk",
    "TooShort",
    "__version__",
    "average_correlation",
    "blend",
    "bootstrap_interval",
    "check_subadditivity",
    "cholesky",
    "condition_number",
    "constant_correlation_target",
    "cornish_fisher_risk",
    "correlation",
    "diagnose",
    "eigenvalues",
    "eigh",
    "empirical_quantile",
    "ewma_volatility",
    "filtered_historical_risk",
    "historical_risk",
    "is_positive_semidefinite",
    "ledoit_wolf",
    "nearest_psd",
    "normal_cdf",
    "normal_pdf",
    "normal_ppf",
    "normal_risk",
    "parametric_risk",
    "portfolio_risk",
    "portfolio_variance",
    "quadratic_form",
    "sample_covariance",
    "sample_expected_shortfall",
    "student_t_cdf",
    "student_t_pdf",
    "student_t_ppf",
    "student_t_risk",
]
